### ISSUE TITLE
Hover do texto selecionado às vezes desaparece do ecrã

### ISSUE THREAD

**Issue by Gil124** [t4zzlerdeveloper/rubium#1]
**Describe the bug**
se eu estiver a escrever num parágrafo e o parágrafo ficar maior do que uma linha quando seleciono texto na segunda linha o hover de texto selecionado sai para a direita do ecrã

**To Reproduce**
1. Criar um parágrafo
2. Escrever texto suficiente até ficar se com duas linhas (sem usar enter)
3. Selecionar texto na segunda linha
4. Observar o popUp fora do sítio

**Expected behavior**
Seria melhor pôr o popup com o x do rato quando estava a selecionar e largou

**Screenshots**
![image](https://github.com/t4zzlerdeveloper/rubium/assets/47061119/a916cc85-76cd-4b6a-824d-4653c3edc5d2)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Vivaldi
 - Version. last

**Smartphone (please complete the following information):**

**Additional context**

**Comment by t4zzlerdeveloper** [comment]
Thank you for reporting this issue, turns out this functionality was still under development and shouldn't be live.

We will disable this feature (taking effect in the next deploy) until it is fully implemented and integrated with the Note Editor, therefore i'm closing this issue and re-opening it when the process of development starts.
